version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.1.0-stretch
    steps:
      - checkout
      - run: npm i
      - run: cd example/empty && npm i
      - run: cd example/basic && npm i
      - run: cd example/blacklisted-licenses && npm i
      - run: npm run test
