version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.1.0-stretch
    steps:
      - checkout
      - run: yarn
      - run: cd example/empty && yarn
      - run: cd example/basic && yarn
      - run: cd example/blacklisted-licenses && yarn
      - run: yarn run test
